name = "astro-solidjs-cloudflare"
compatibility_date = "2024-01-01"

# Uncomment and configure these bindings as needed:

# D1 Database
 [[d1_databases]]
 binding = "DB"
 database_name = "test"
 database_id = "22d86356-69ed-4aef-9892-3ed62ba427f1"

## KV Namespace
#[[kv_namespaces]]
#binding = "SESSION"
#id = "your-session-kv-namespace-id"

# Durable Objects
# [[durable_objects.bindings]]
# name = "COUNTER"
# class_name = "Counter"

# R2 Bucket
# [[r2_buckets]]
# binding = "R2"
# bucket_name = "my-bucket"